language: node_js
sudo: false
node_js:
- '6'
addons:
  apt:
    packages:
    - git
script: npm test
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: fhgyemfbz/33jUIG0VL9gKTQ668wPgXBqflIaPAT+M5gZnQRWKugGekS1WWY1XcypbZuRhSghCTCk8VwIM6aXD6OqKTKlcDTnDsNbvKBUZG0R7P7Q3mKkWcwYmXBwCi/Jfy8jG28MkjdwHsnZ7fydN22ILgnZcIJU55DwaTUpOo=
  on:
    tags: true
    repo: noflo/noflo-git
